#include "interface.h"

#include "debug.h"

#ifdef I2CIP_USE_GUARANTEES
I2CIP_GUARANTEE_DEFINE(I2CIP::Device, I2CIP_GUARANTEE_DEVICE);
I2CIP_GUARANTEE_DEFINE(I2CIP::InputGetter, I2CIP_GUARANTEE_INPUT);
I2CIP_GUARANTEE_DEFINE(I2CIP::OutputSetter, I2CIP_GUARANTEE_OUTPUT);
#endif